---
title: "R for Medical Research"
author: "Matt Broerman"
date: "February 20, 2024"
---

## Updates

**Mar. 11**

Advanced tutorials for the last week are posted, these correspond to some requests by attendees. Check back here for further ones.

All the main course content is now updated.

**Feb. 21**

We secured a room for most days, E1248 BST.

I decided to create a new project space.

**Feb. 28**

Sessions 0, 1 videos are posted.

## Description

This workshop is hosted by the PACCSM Pulmonary Translational Research Core (PTRC). The purpose is to

-   get you familiar enough with R so you can direct further study
-   focus on in-session hands-on exercises with real data
-   provide a work environment so you don't need to install software
-   start with best practices

The design is flipped so sessions are hands-on while the materials are preparatory and optional.

## Materials

All the materials we'll use in this workshop are in this RStudio project. You can open this project in your browser without needing to install or download anything on your computer. Open this RStudio.cloud project (you'll need to create a free account really quick):

<p class="text-center">

<a class="btn btn-info btn-lg" target="_blank" href="https://posit.cloud/content/7647057">{{< fa brands r-project >}}  posit.cloud project</a>

</p>

## Schedule

This workshop is virtual-first, but we will meet in-person pending location availability.

We will use Pitt's Zoom [service](https://pitt.zoom.us/j/97006092281) and make the recordings available internally.

| Date (Weekly) |     | Topic                                     | Room      | Slides                                                  | Links                                                                                                                                                                    | Video                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|-------|-------|-------|-------|-------|-------|------------------------------|
| 02-20-2024    | 0   | Installation, packages, basics, questions | NA        | [Post](pres_r4med_rstudio/)                             | [R](https://www.r-project.org/), [RStudio](https://posit.co/download/rstudio-desktop/)                                                                                   | [Pitt](https://pitt.zoom.us/rec/share/dDz-FnEBd3iXiR_6YFWRsizs9sfL8kIWV405qYDYOjfBstET-Vdg3p4P1j0m62K9.-I1Ceur6pHRozPem), [UPMC](https://upmchs-my.sharepoint.com/:v:/g/personal/broermanmj_upmc_edu/EVAyGJqsQnxOhGfSErqmIaUBYQD5WunJpbq16htK5B3jjA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=UjzGc0)                |
| 02-27-2024    | 1   | Clinical trials and data manipulation     | E1248 BST | [Pre](pres_r4med_data/), [Post](pres_r4med_vec/)        | [medicaldata](https://higgi13425.github.io/medicaldata/index.html), [dplyr](https://dplyr.tidyverse.org/), [pipe style](https://r4ds.hadley.nz/workflow-style#sec-pipes) | [Pitt](https://pitt.zoom.us/rec/share/bi-xXeGb3HiIjsWlj-YcUD0hdAhhI09fbCwKTguIYCvzEJvk_6jlYY9GXN98u5cn.adISKQMN6RRMmZKv), [UPMC](https://upmchs-my.sharepoint.com/:v:/g/personal/broermanmj_upmc_edu/EQFa1ZsrN-5EjNazl-SjjdoBAojsWkwNhxhqLjYyawZ63w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=3RxPJu)                |
| 03-05-2024    | 2   | Tables and reports                        | E1248 BST | [Pre](pres_r4med_fgs/)                                  | [gtsummary](https://www.danieldsjoberg.com/gtsummary/), [quarto](https://quarto.org/)                                                                                    | [Pitt](https://pitt.zoom.us/rec/play/ske0eh4JSzPTUEtESxVwOB6AnmvGbldGotdt4gqtras_EhmwdjZ7NG_ByiOIFuTAMtFmF9rpUyAteyak.ejHG18086ludFWve), [UPMC](https://upmchs-my.sharepoint.com/:v:/g/personal/broermanmj_upmc_edu/EXUqajobXkJKtwtzVQaCzokBEoOY2gApdWJ2eYtj1h_CuQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=qgYSY7) |
| 03-12-2024    | 3   | EHR data and joining it together          | E1248 BST | [Pre](pres_r4med_shape/)                                | [MIMIC-IV](https://physionet.org/content/mimic-iv-demo/2.2/), [tidyr](https://tidyr.tidyverse.org/)                                                                      | Pitt, UPMC                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 03-19-2024    | 4   | Summarizing and plotting                  | E1248 BST | [Pre](pres_r4med_plot/)                                 | [dplyr](https://dplyr.tidyverse.org/), [ggplot2](https://ggplot2.tidyverse.org/index.html)                                                                               | Pitt, UPMC                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 03-26-2024    |     | Cancelled                                 |           |                                                         |                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| 04-02-2024    | 5   | Linear, logistic, and cox models.         | E1248 BST | [Pre](pres_r4med_mod/)                                  | [survival](https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html)                                                                                    | Pitt, UPMC                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 04-09-2024    | 6   | Review topics of interest                 | E1248 BST |                                                         | ?                                                                                                                                                                        | Pitt, UPMC                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| 04-16-2024    | 7   | basics of scRNAseq, causal inference      | E1248 BST | [Tut1](tut_mediation.html), [Tut2](tut_sc-cxg-cen.html) | Seurat, mediation                                                                                                                                                        | Pitt, UPMC                                                                                                                                                                                                                                                                                                                                                                                                                                                               |

## Registration

Registration is closed.

<!-- <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd2vOcN5INRE3djFO-1umGc7HeZ0BIl1TUkJaMEJS7O-nE1XA/viewform?embedded=true" width="640" height="1759" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe> -->
